server:
  port: 8080
spring:
  freemarker:
    enabled: true
uid:
  # Retrieve these values from the UID Manager portal
  client-id: ${UID_CLIENT_ID:O997SLMHGIQPZIWZTRUA}
  client-secret: ${UID_CLIENT_SECRET:0p9rxCZl55UmgXs0EAhaAfL8D8WKzmZgKiT9e3mF}
  api-host: ${UID_API_HOST:api-gw.uid1.dev.uidpreview.com}
  redirect-url: ${UID_REDIRECT_URL:http://localhost:8080/callback}
